### ISSUE TITLE
What should the "do no evil" consist of?

### ISSUE THREAD

**Issue by eklem** [eklem/software-code-of-conduct#1]
I guess this will be a little opinionated. What is defined as good and fair differs in different cultures, but we have a set of [human rights](http://www.un.org/en/universal-declaration-human-rights/) to look at?

**Comment by eklem** [comment]
Is this something for you to contribute on, @babadofar ?

**Comment by babadofar** [comment]
thanks for asking!  No stealing, no killing, no lying. Those are the most basic universal moral rules, i believe. Also I recently read Elastic's community code of conduct with great interest. It has a large section on harassment. https://www.elastic.co/community/codeofconduct

**Comment by eklem** [comment]
Nice input! @fergiemcdowall's reference story had [lying that lead to killing](https://hackernoon.com/why-isnt-software-engineering-a-profession-68d1900112fc#.euvr0f23n). I'll start with that and add the harassment part. That's also something I like with [Nodejs' code of conduct](https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md)

**Comment by eklem** [comment]
Added the bare minimum =)
https://github.com/eklem/software-code-of-conduct/commit/51c3b54bcdfe378a3764e6c3ae06f50475094f81
